name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install LlamaLint
        run: |
          python -m pip install --upgrade pip
          pip install llamalint
          
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install JS/TS formatting dependencies
        run: |
          npm install -g prettier eslint typescript
          
      - name: Run LlamaLint
        run: |
          llamalint lint --output-format json > llamalint-results.json
          
      - name: Upload lint results
        uses: actions/upload-artifact@v3
        with:
          name: llamalint-results
          path: llamalint-results.json
          
      - name: Check for errors
        run: |
          # Check if there are any errors in the JSON output
          if grep -q '"severity":"error"' llamalint-results.json; then
            echo "Linting errors found. Check the lint results artifact for details."
            exit 1
          fi 